### PR TITLE
Fixed #3, applied DRY

### LINKED ISSUE #3: Handle yii\db\Expression
Skip attributes behavior should be done before comparing values. 

If you use an expression in other behaviors history will fail.

Explanation.

When a behavior uses a *db expression*  to set the value, history behavior fails. That is because it expects that all values are comparable. 
```php
'timestamp' => [
                'class' => TimestampBehavior::className(),
                'value' => new \yii\db\Expression('NOW()'),
            ],
```

### PR DESCRIPTION
**Pull request by Eseperio**
Fixes a problem when other behaviors use an expression as value.
Also DRY has been applied to the behavior.

### CODE REVIEW

**Comment by bupy7** [comment]
Thanks for your contribution, its cool, but I cannot merge its because of too much changes. It need tests. Could you please make another pull-request only for the skip attributes to merge it? DRY I will check not quick (I have much work). Or, you can add the tests for it (Codeception or PHPUnit as you want).

**Comment by Eseperio** [comment]
Nothing has changed on the data structure. The only thing that changes is that entity array data was defined almost equal in all cases of the switch statement. Now data its defined before switch statement, and then, on each switch case those parameters that really change (event, old_value, new_value...) are defined. It seems really messy on github code comparison, but functionality has not changed.

**Comment by bupy7** [comment]
Could you please upgrade your pull-request and send its again?

**Comment by bupy7** [comment]
Closed by cause have not activity.

**Pull request closed without merging**
